### ISSUE TITLE
Miner Never Runs!!

### ISSUE THREAD

**Issue by DedSec002** [theapache64/coin_hive_android_sdk#4]
Hi,

Still not sure why the miner dont work on my app.

Please help me out.

Thank you

**Comment by theapache64** [comment]
Internet permission enabled ?

**Comment by theapache64** [comment]
Did you solve the issue ?

**Comment by DedSec002** [comment]
Hi,

Thank you for the response.. Yes I have added the internet permission to my AndriodManifest.xml..

Still the miner wont start while using the app... 

Further help is appreciated...

**Comment by theapache64** [comment]
Could you please paste your Activity source code (which extends BaseCoinHiveActivity) ?

**Comment by Letme** [comment]
I think coinhive/src/main/java/com/theah64/coinhive/BaseCoinHiveActivity.java#L56 should have startMining() instead of stopMining(). Want me to submit a PR, or will you quickfix it?

I think this is the reason current runner never runs.

**Comment by DedSec002** [comment]
Letme@

Could you please add the PR and also help the steps to change this

Thank you

**Comment by theapache64** [comment]
Hey @Letme , thank you for the PR. but that's not the reason why the miner not runs for DedSec. @DedSec002 can you please show me your code or mail me the zip to theapache64@gmail.com. I can help you then.

**Comment by DedSec002** [comment]
@theapache64  , I have sent you my code through email.

Awaiting your response....

**Comment by theapache64** [comment]
Yeah i got the screenshots. The problem is not in the SDK but in your code. 
You've initialised the SDK in your  Activity, which should be done in Application instance. and then extend your MainActivity from 'BaseCoinHiveActivity' instead of your 'BaseApp'. Please check the sample source code for clear reference.

**Comment by DedSec002** [comment]
@theapache64 ,

Thank you for your response. I am able to run the miner now.

But, the problem is the way you have given example in your documentation is bit confusing.

As you're trying to put generic base class example and also each activity class example as a single example code which made me confused as a reader to implement the same.

I have attached my code screenshots when my code started running with your miner SDK.

However, my suggestion is or improvement that I can tell is that, please separate the examples by base class approach and each activity approach.

Thank you for all your help..

I will just get back to you with my user experiences later.
![screenshot2](https://user-images.githubusercontent.com/29062922/32700343-9b8ed57e-c7e9-11e7-9b86-fb70041c26f8.PNG)
![screenshot1](https://user-images.githubusercontent.com/29062922/32700344-9bcb05da-c7e9-11e7-8e39-ec0ca622700e.PNG)

**Comment by Letme** [comment]
OK, I seem to have a same problem, but I have more inline code with the example as what it is here.

In `AndroidManifest.xml` I have added to application `android:name=".App"`, which calls class `public class App extends Application` (which inside has onCreate with CoinHive object). Then I have a second activity (one that opens after the MAIN, since I did not want to start mining on MAIN) which is `public class GameScreen extends BaseCoinHiveActivity implements View.OnTouchListener`. What is funny is that when I stop `GameScreen` activity it prints: `I/System.out: Mining stopped`, but leaving it running I see nothing. I have confirmed App runs, so CoinHive object should be initialized, but calling `StartMining()` in GameScreen activity just crashes with `NullPointerException`.

The 1.0.7 is still not pushed to maven :smile:

**Comment by Letme** [comment]
Just as I posted I tried to extend my MAIN - LUNCHER activity with `BaseCoinHiveActivity` and it all started to work. I think I don't know enough to provide a PR for this so that miner would only start on the second activity which is run from MAIN/LUNCHER activity.

**Comment by theapache64** [comment]
@Letme Am sorry, have been AFK. I've pushed v1.0.7 to maven. (7fd8c5409422d1a23e738cd7e8bce951a372e320) (am sorry for the delay).
